# Generated by Django 5.2.11 on 2026-02-05 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatsession_user_document_user_systemprompt_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='citations',
            field=models.JSONField(blank=True, default=list, help_text='List of source snippets used to generate this answer.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0, help_text='Number of vector chunks generated from this file.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, help_text='Stores traceback if indexing fails.', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(help_text='Absolute path to the raw file on disk.', max_length=512),
        ),
        migrations.AlterField(
            model_name='document',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', help_text='Current state of the document in the RAG pipeline.', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The owner of this document. Ensures data isolation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
